"""foreign key in imageurl

Revision ID: 477d8825ba0e
Revises: a03c982184d9
Create Date: 2023-11-27 11:56:11.970091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477d8825ba0e'
down_revision = 'a03c982184d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imageurls', schema=None) as batch_op:
        batch_op.drop_constraint('fk_imageurls_card_id_mtgcards', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_imageurls_card_id_cardfaces'), 'cardfaces', ['card_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imageurls', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_imageurls_card_id_cardfaces'), type_='foreignkey')
        batch_op.create_foreign_key('fk_imageurls_card_id_mtgcards', 'mtgcards', ['card_id'], ['id'])

    # ### end Alembic commands ###
