"""first migrate

Revision ID: 60149aa9cdbb
Revises: 
Create Date: 2023-11-16 14:58:09.930730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60149aa9cdbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtgcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_uris', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mtgcards'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('mtgdecks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mtgdecks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mtgdecks'))
    )
    op.create_table('mtgdeckcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('mtgcard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['mtgdecks.id'], name=op.f('fk_mtgdeckcards_deck_id_mtgdecks')),
    sa.ForeignKeyConstraint(['mtgcard_id'], ['mtgcards.id'], name=op.f('fk_mtgdeckcards_mtgcard_id_mtgcards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mtgdeckcards'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mtgdeckcards')
    op.drop_table('mtgdecks')
    op.drop_table('users')
    op.drop_table('mtgcards')
    # ### end Alembic commands ###
