"""imageurls

Revision ID: a03c982184d9
Revises: bba5d08334e1
Create Date: 2023-11-27 11:38:36.663745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03c982184d9'
down_revision = 'bba5d08334e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imageurls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('small', sa.String(), nullable=True),
    sa.Column('normal', sa.String(), nullable=True),
    sa.Column('large', sa.String(), nullable=True),
    sa.Column('png', sa.String(), nullable=True),
    sa.Column('art_crop', sa.String(), nullable=True),
    sa.Column('border_crop', sa.String(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['mtgcards.id'], name=op.f('fk_imageurls_card_id_mtgcards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imageurls'))
    )
    with op.batch_alter_table('cardfaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('image_uris')

    with op.batch_alter_table('mtgcards', schema=None) as batch_op:
        batch_op.drop_column('image_uris')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mtgcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_uris', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('cardfaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_uris', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('name')

    op.drop_table('imageurls')
    # ### end Alembic commands ###
