"""attribute fix

Revision ID: a1397e450d91
Revises: 8a31931b03f0
Create Date: 2023-11-28 11:49:42.177139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1397e450d91'
down_revision = '8a31931b03f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yugideckcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yugicard_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_yugideckcards_mtgcard_id_yugicards', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_yugideckcards_yugicard_id_yugicards'), 'yugicards', ['yugicard_id'], ['id'])
        batch_op.drop_column('mtgcard_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yugideckcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mtgcard_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_yugideckcards_yugicard_id_yugicards'), type_='foreignkey')
        batch_op.create_foreign_key('fk_yugideckcards_mtgcard_id_yugicards', 'yugicards', ['mtgcard_id'], ['id'])
        batch_op.drop_column('yugicard_id')

    # ### end Alembic commands ###
